---
- name: Deploy auto DHCP detection for Proxmox USB-C adapters
  hosts: proxmox
  become: true
  tasks:

    - name: Disable IPv6 system-wide via sysctl
      copy:
        dest: /etc/sysctl.d/99-disable-ipv6.conf
        content: |
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1
        mode: '0644'

    - name: Apply sysctl changes
      command: sysctl --system

    - name: Copy DHCP script with interface support
      copy:
        src: files/auto-dhcp.sh
        dest: /usr/local/bin/auto-dhcp.sh
        mode: '0755'

    - name: Copy systemd templated service
      copy:
        src: files/auto-dhcp.service
        dest: /etc/systemd/system/auto-dhcp.service
        mode: '0644'

    - name: Copy systemd templated timer
      copy:
        src: files/auto-dhcp.timer
        dest: /etc/systemd/system/auto-dhcp.timer
        mode: '0644'

    - name: Reload systemd service & timer
      shell: |
        systemctl daemon-reexec
        systemctl daemon-reload
        systemctl enable --now auto-dhcp.timer
